version: "3"

services:
  nginx:
    image: nginx:1.13.0
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
    links:
      - php

  php:
    image: php:7.1.6-fpm
    volumes:
      - .:/srv/praline-test
      - ../praline:/srv/praline
      - /var/log/php:/var/log/php
    links:
      - fluentd

  fluentd:
    image: fluent/fluentd:v0.12-debian
    volumes:
      - ./docker/fluentd.conf:/fluentd/etc/fluent.conf
      - /var/log/fluentd:/fluentd/log
